#pragma once
#define IDI_APPICON 101
#define IDR_TRAYMENU 102
#define IDR_HEADER_PNG 103
#define IDR_SLIDER_BRIGHTNESS 104
#define IDR_SLIDER_CONTRAST 105
#define IDR_SLIDER_GAMMA 106
#define IDR_SLIDER_VIBRANCE 107
#define IDR_SLIDER_HUE 108
#define IDR_SECTION_PROFILES 109
#define IDR_SECTION_PROFILE_SETTINGS 110
#define IDR_SECTION_APP_SETTINGS 111
#define IDR_NVIDIA_PNG 112
