#pragma once
#define IDI_APPICON 101
#define IDI_APPICON_TRANSPARENT  102
#define IDR_TRAYMENU 103
#define IDR_HEADER_PNG 104
#define IDR_SLIDER_BRIGHTNESS 105
#define IDR_SLIDER_CONTRAST 106
#define IDR_SLIDER_GAMMA 107
#define IDR_SLIDER_VIBRANCE 108
#define IDR_SLIDER_HUE 109
#define IDR_SECTION_PROFILES 110
#define IDR_SECTION_PROFILE_SETTINGS 111
#define IDR_SECTION_APP_SETTINGS 112
#define IDR_NVIDIA_PNG 113
