#pragma once
#define IDI_APPICON 101
#define IDR_TRAYMENU 102
#define IDR_HEADER_PNG 103
#define IDR_SLIDER_BRIGHTNESS 104
#define IDR_SLIDER_CONTRAST 105
#define IDR_SLIDER_GAMMA 106
#define IDR_SLIDER_VIBRANCE 107
#define IDR_SLIDER_HUE 108
